services:
  ultrasinger:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../input:/app/UltraSinger/input
      - ../output:/app/UltraSinger/output
      - ../cookies.txt:/app/UltraSinger/cookies.txt:ro
    stdin_open: true
    tty: true
