"""Cookie extraction from QWebEngine and Netscape-format export for yt-dlp."""

import logging
from pathlib import Path

from PySide6.QtCore import QObject, Signal
from PySide6.QtNetwork import QNetworkCookie
from PySide6.QtWebEngineCore import QWebEngineCookieStore, QWebEngineProfile

logger = logging.getLogger(__name__)


class CookieManager(QObject):
    """Manages browser cookies: collection, export to Netscape format, clearing."""

    cookies_changed = Signal()

    def __init__(self, profile: QWebEngineProfile, parent=None):
        super().__init__(parent)
        self._cookies: list[QNetworkCookie] = []
        self._profile = profile
        self._store: QWebEngineCookieStore = profile.cookieStore()
        self._store.cookieAdded.connect(self._on_cookie_added)
        self._store.cookieRemoved.connect(self._on_cookie_removed)
        self._store.loadAllCookies()

    def _on_cookie_added(self, cookie: QNetworkCookie):
        # Avoid duplicates
        for i, existing in enumerate(self._cookies):
            if (
                existing.name() == cookie.name()
                and existing.domain() == cookie.domain()
                and existing.path() == cookie.path()
            ):
                self._cookies[i] = cookie
                self.cookies_changed.emit()
                return
        self._cookies.append(cookie)
        self.cookies_changed.emit()

    def _on_cookie_removed(self, cookie: QNetworkCookie):
        self._cookies = [
            c
            for c in self._cookies
            if not (
                c.name() == cookie.name()
                and c.domain() == cookie.domain()
                and c.path() == cookie.path()
            )
        ]
        self.cookies_changed.emit()

    @property
    def video_cookie_count(self) -> int:
        """Number of cookies for the video platform domain."""
        return sum(
            1
            for c in self._cookies
            if ".youtube.com" in c.domain() or "youtube.com" in c.domain()
        )

    @property
    def has_video_cookies(self) -> bool:
        return self.video_cookie_count > 0

    def export_netscape(self, filepath: str | Path) -> Path:
        """Export all cookies in Netscape format compatible with yt-dlp.

        Returns the path to the written file.
        """
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)

        lines = ["# Netscape HTTP Cookie File", "# Generated by UltraSinger GUI", ""]
        for cookie in self._cookies:
            domain = cookie.domain()
            if not domain:
                continue
            include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
            path = cookie.path() or "/"
            secure = "TRUE" if cookie.isSecure() else "FALSE"
            expiry_dt = cookie.expirationDate()
            expiry = (
                str(int(expiry_dt.toSecsSinceEpoch()))
                if expiry_dt.isValid()
                else "0"
            )
            name = bytes(cookie.name()).decode("utf-8", errors="replace")
            value = bytes(cookie.value()).decode("utf-8", errors="replace")
            lines.append(
                f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}"
            )

        filepath.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Exported %d cookies to %s", len(self._cookies), filepath)
        return filepath

    def clear_all(self):
        """Delete all cookies from the browser profile."""
        self._store.deleteAllCookies()
        self._cookies.clear()
        self.cookies_changed.emit()
        logger.info("All browser cookies cleared")
