"""Intercept googlevideo.com media requests from QWebEngine.

Captures pre-signed audio stream URLs that the platform's player resolves
internally.  These URLs bypass yt-dlp entirely — they were generated by
the real Chromium browser, so the platform cannot distinguish them from a
normal user watching a video.

The captured URLs can be passed to ffmpeg for direct download, avoiding
bot detection that yt-dlp triggers.
"""

from __future__ import annotations

import logging
import re
import time
from dataclasses import dataclass, field
from urllib.parse import parse_qs, urlencode, urlparse, urlunparse

from PySide6.QtCore import QObject, Signal
from PySide6.QtWebEngineCore import (
    QWebEngineUrlRequestInfo,
    QWebEngineUrlRequestInterceptor,
)

logger = logging.getLogger(__name__)

# Known audio-only itags (https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/youtube/_video.py)
_AUDIO_ITAGS = {
    139, 140, 141,       # m4a AAC
    171, 172,            # webm Vorbis
    249, 250, 251,       # webm Opus
    256, 258,            # m4a AAC HE
    325, 328,            # m4a AC-3 / E-AC-3
    338,                 # webm Opus (immersive)
}

# Progressive (muxed video+audio) itags — captured as FALLBACK when no
# separate audio stream is available.  With SABR delivery the adaptive
# streams arrive as opaque binary POST responses (no capturable URL);
# the player then still fetches a classic progressive stream we can use.
# Only the audio track (AAC) is extracted downstream.
_MUXED_ITAGS = {
    18,                  # mp4 360p H.264 + AAC 96k
    22,                  # mp4 720p H.264 + AAC 192k (rarely served)
    59,                  # mp4 480p H.264 + AAC
}


@dataclass
class CapturedAudioStream:
    """A captured, pre-signed audio stream URL from googlevideo.com."""

    url: str                     # Full URL without range parameter
    video_id: str                # video platform video ID
    itag: int = 0                # Stream format identifier
    mime_type: str = ""          # e.g. "audio/webm"
    expire_time: int = 0         # Unix timestamp from &expire= parameter
    captured_at: float = field(default_factory=time.time)
    is_muxed: bool = False       # Progressive video+audio stream (fallback);
                                 # only the audio track is used downstream

    @property
    def is_expired(self) -> bool:
        """Check if the URL has expired (with 60s safety margin)."""
        if self.expire_time == 0:
            return False
        return time.time() > self.expire_time - 60

    @property
    def seconds_until_expiry(self) -> float:
        """Seconds until expiry (negative if already expired)."""
        if self.expire_time == 0:
            return float("inf")
        return self.expire_time - 60 - time.time()


def _extract_video_id_from_url(url: str) -> str:
    """Extract the video ID from a googlevideo.com URL.

    googlevideo.com URLs don't directly contain the video ID.
    We use the ``id`` parameter as a stable, unique stream identifier
    instead.  The actual video ID mapping is handled by the
    browser tab (which knows which page the user is watching).
    """
    params = parse_qs(urlparse(url).query)
    return params.get("id", [""])[0]


def _strip_range_params(url: str) -> str:
    """Remove byte-range parameters so ffmpeg downloads the full file.

    The platform's chunk requests include ``range``, ``rn`` (request number),
    and ``rbuf`` parameters that are only meaningful for MSE playback.
    """
    parsed = urlparse(url)
    params = parse_qs(parsed.query, keep_blank_values=True)
    for key in ("range", "rn", "rbuf"):
        params.pop(key, None)
    # Re-encode with doseq=True since parse_qs returns lists
    clean_query = urlencode(params, doseq=True)
    return urlunparse(parsed._replace(query=clean_query))


def _is_audio_request(url: str) -> bool:
    """Check if a googlevideo.com URL is for an audio stream."""
    params = parse_qs(urlparse(url).query)

    # Check mime parameter: mime=audio%2Fwebm or mime=audio%2Fmp4
    mime = params.get("mime", [""])[0]
    if mime.startswith("audio/"):
        return True

    # Fallback: check itag
    itag_str = params.get("itag", [""])[0]
    if itag_str.isdigit() and int(itag_str) in _AUDIO_ITAGS:
        return True

    return False


def _is_muxed_request(url: str) -> bool:
    """Check if a URL is for a progressive (muxed video+audio) stream."""
    params = parse_qs(urlparse(url).query)
    itag_str = params.get("itag", [""])[0]
    return itag_str.isdigit() and int(itag_str) in _MUXED_ITAGS


class MediaInterceptor(QWebEngineUrlRequestInterceptor):
    """Intercepts googlevideo.com media requests to capture audio URLs.

    Install on a QWebEngineProfile to passively capture audio stream
    URLs as the user browses the platform.  The interceptor does NOT block
    or modify any requests — it only reads the URL.

    Signals:
        audio_captured(video_id, url): Emitted when a new audio stream
            URL is captured for a video.
    """

    # Signal must be on a QObject, not directly on the interceptor
    # (QWebEngineUrlRequestInterceptor IS a QObject in PySide6)
    audio_captured = Signal(object)  # CapturedAudioStream
    po_token_captured = Signal(str)  # GVS Proof-of-Origin token

    def __init__(self, parent: QObject | None = None):
        super().__init__(parent)
        # Streams keyed by video platform video ID (set externally by BrowserTab)
        self._streams: dict[str, CapturedAudioStream] = {}
        # Diagnostics: log unclassified googlevideo requests (deduplicated,
        # capped) so a broken capture (e.g. the platform switching the embedded
        # player to progressive-only or SABR delivery) is visible in the log
        self._diag_seen: set[str] = set()
        # Latest GVS Proof-of-Origin token seen on media requests.  It is
        # session-bound (not per-video) and lets yt-dlp fetch the full
        # format list instead of the limited anonymous fallback.
        self._po_token: str = ""

    def interceptRequest(self, info):
        """Called for every HTTP request made by QWebEngine.

        IMPORTANT: This runs on Chromium's IO thread.  Must be fast
        and non-blocking — no file I/O, no heavy computation.
        """
        url = info.requestUrl()
        host = url.host()
        path = url.path()

        # Media traffic can come from *.googlevideo.com (classic) or be
        # proxied through other hosts (e.g. *.youtube.com/videoplayback).
        # Chromium also tags <video>/<audio> element loads as Media.
        is_media_host = host.endswith("googlevideo.com")
        is_media_path = (
            "videoplayback" in path
            or "initplayback" in path
            or path.startswith("/ump")
        )
        is_media_type = (
            info.resourceType()
            == QWebEngineUrlRequestInfo.ResourceType.ResourceTypeMedia
        )

        # Fast path: skip anything that cannot be media traffic
        if not is_media_host and not is_media_path and not is_media_type:
            return

        url_str = url.toString()

        # Harvest the GVS PO token from ANY media request (including SABR
        # POSTs, which are otherwise useless to us).  It is the key that
        # lets yt-dlp download full-quality formats with the same session.
        params = parse_qs(urlparse(url_str).query)
        pot = params.get("pot", [""])[0]
        if pot and pot != self._po_token:
            self._po_token = pot
            logger.info("Captured GVS PO token (%d chars)", len(pot))
            self.po_token_captured.emit(pot)

        is_audio = _is_audio_request(url_str)
        is_muxed = not is_audio and _is_muxed_request(url_str)
        if not is_audio and not is_muxed:
            if len(self._diag_seen) < 20:
                rt = info.resourceType()
                sig = (
                    f"host={host}"
                    f" path={path}"
                    f" mime={params.get('mime', [''])[0]}"
                    f" itag={params.get('itag', [''])[0]}"
                    f" sabr={params.get('sabr', [''])[0]}"
                    f" pot_len={len(pot)}"
                    f" type={getattr(rt, 'name', rt)}"
                    f" method={bytes(info.requestMethod()).decode('ascii', 'replace')}"
                )
                if sig not in self._diag_seen:
                    self._diag_seen.add(sig)
                    logger.info(
                        "media-ish request NOT classified as audio: %s", sig
                    )
            return

        # Strip range params to get a full-file download URL
        clean_url = _strip_range_params(url_str)

        # Extract metadata from URL params (defensive: non-numeric → 0)
        params = parse_qs(urlparse(url_str).query)
        stream_id = params.get("id", [""])[0]
        mime = params.get("mime", [""])[0]
        try:
            itag = int(params.get("itag", ["0"])[0] or 0)
        except (ValueError, TypeError):
            itag = 0
        try:
            expire = int(params.get("expire", ["0"])[0] or 0)
        except (ValueError, TypeError):
            expire = 0

        stream = CapturedAudioStream(
            url=clean_url,
            video_id=stream_id,  # googlevideo stream ID, not YT video ID
            itag=itag,
            mime_type=mime,
            expire_time=expire,
            captured_at=time.time(),
            is_muxed=is_muxed,
        )

        logger.debug(
            "Captured %s stream (itag=%d, mime=%s, expires in %.0fs)",
            "muxed fallback" if is_muxed else "audio",
            itag, mime, stream.seconds_until_expiry,
        )
        # Emit the exact stream object — the receiver assigns it to a
        # video ID on the GUI thread, avoiding a shared mutable slot.
        self.audio_captured.emit(stream)

    def assign_to_video(self, video_id: str, stream: CapturedAudioStream):
        """Associate a specific captured stream with a video ID.

        Called by BrowserTab on the GUI thread when it knows which
        video is playing.  Receives the exact stream object from the
        signal, so there is no race with subsequent interceptor calls.
        """
        if video_id and stream:
            existing = self._streams.get(video_id)
            # A muxed fallback stream must never replace a pure audio
            # stream (better quality) that is still valid
            if (
                stream.is_muxed
                and existing is not None
                and not existing.is_muxed
                and not existing.is_expired
            ):
                return
            is_new = existing is None
            self._streams[video_id] = stream
            if is_new:
                logger.info(
                    "First %s stream captured for video %s "
                    "(itag=%d, mime=%s)",
                    "muxed fallback" if stream.is_muxed else "audio",
                    video_id, stream.itag, stream.mime_type,
                )
            else:
                logger.debug(
                    "Assigned stream to video %s (itag=%d)",
                    video_id, stream.itag,
                )

    def get_stream(self, video_id: str) -> CapturedAudioStream | None:
        """Get the captured audio stream for a video ID, if available."""
        stream, _ = self.get_stream_with_status(video_id)
        return stream

    def get_stream_with_status(
        self, video_id: str
    ) -> tuple[CapturedAudioStream | None, str]:
        """Get the stream plus a status for user-facing diagnostics.

        Returns (stream, status) where status is one of:
        ``"ok"`` — usable stream, ``"missing"`` — nothing was ever
        captured for this video, ``"expired"`` — a stream was captured
        but its signed URL has expired.
        """
        stream = self._streams.get(video_id)
        if stream is None:
            return None, "missing"
        if stream.is_expired:
            del self._streams[video_id]
            logger.debug("Expired stream for %s removed", video_id)
            return None, "expired"
        return stream, "ok"

    def get_po_token(self) -> str:
        """Latest GVS PO token captured from the browser session ('' if none)."""
        return self._po_token

    def get_all_streams(self) -> dict[str, CapturedAudioStream]:
        """Get all non-expired captured streams."""
        # Prune expired
        expired = [
            vid for vid, s in self._streams.items() if s.is_expired
        ]
        for vid in expired:
            del self._streams[vid]
        return dict(self._streams)

    def clear(self):
        """Clear all captured streams."""
        self._streams.clear()
