"""Pre-download audio from intercepted googlevideo.com URLs via ffmpeg.

This module downloads audio directly using ffmpeg with the pre-signed
URL that the embedded Chromium browser resolved.  Since the URL was
generated by a real browser, YouTube cannot distinguish it from normal
playback — no bot detection is triggered.

Falls back to yt-dlp when no intercepted URL is available.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path

from PySide6.QtCore import QObject, QThread, Signal

logger = logging.getLogger(__name__)


class MediaDownloadWorker(QObject):
    """Downloads audio from an intercepted URL using ffmpeg.

    Runs in a QThread to avoid blocking the GUI.

    Signals:
        finished(success, audio_path, error_msg)
        progress(message)
    """

    finished = Signal(bool, str, str)  # success, audio_path, error_msg
    progress = Signal(str)

    def __init__(
        self,
        audio_url: str,
        output_path: str,
        parent: QObject | None = None,
    ):
        super().__init__(parent)
        self._audio_url = audio_url
        self._output_path = output_path
        self._process: subprocess.Popen | None = None

    def run(self):
        """Download the audio stream via ffmpeg (stream copy, no re-encode)."""
        ffmpeg = _find_ffmpeg()
        if not ffmpeg:
            self.finished.emit(
                False, "", "ffmpeg not found in PATH or standard locations"
            )
            return

        self.progress.emit("[Download] Downloading audio via browser stream...")

        cmd = [
            str(ffmpeg),
            "-y",                    # Overwrite output
            "-i", self._audio_url,   # Pre-signed googlevideo URL
            "-c", "copy",            # Stream copy — no re-encode
            "-vn",                   # No video
            str(self._output_path),
        ]

        try:
            self._process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
            )
            _, stderr = self._process.communicate(timeout=300)
            rc = self._process.returncode

            if rc == 0 and Path(self._output_path).exists():
                size_mb = Path(self._output_path).stat().st_size / (1024 * 1024)
                self.progress.emit(
                    f"[Download] Audio downloaded ({size_mb:.1f} MB)"
                )
                self.finished.emit(True, self._output_path, "")
            else:
                err = stderr.decode(errors="replace").strip()[-500:]
                self.finished.emit(False, "", f"ffmpeg failed (rc={rc}): {err}")

        except subprocess.TimeoutExpired:
            if self._process:
                self._process.kill()
            self.finished.emit(False, "", "ffmpeg download timed out (5 min)")
        except OSError as e:
            self.finished.emit(False, "", f"ffmpeg error: {e}")
        finally:
            self._process = None

    def cancel(self):
        """Cancel the running download."""
        if self._process:
            self._process.kill()


def _find_ffmpeg() -> Path | None:
    """Find ffmpeg executable."""
    # Check PATH first
    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg:
        return Path(ffmpeg)

    # Common Windows locations
    for p in [Path(r"c:\bin\ffmpeg.exe"), Path(r"c:\ffmpeg\bin\ffmpeg.exe")]:
        if p.exists():
            return p

    return None


def start_media_download(
    audio_url: str,
    output_path: str,
    parent: QObject | None = None,
) -> tuple[QThread, MediaDownloadWorker]:
    """Start a media download in a background thread.

    Returns the (thread, worker) tuple.  Connect to worker.finished
    and worker.progress signals before calling thread.start().
    """
    thread = QThread(parent)
    worker = MediaDownloadWorker(audio_url, output_path)
    worker.moveToThread(thread)
    thread.started.connect(worker.run)
    worker.finished.connect(thread.quit)
    return thread, worker
