"""Intercept googlevideo.com media requests from QWebEngine.

Captures pre-signed audio stream URLs that YouTube's player resolves
internally.  These URLs bypass yt-dlp entirely — they were generated by
the real Chromium browser, so YouTube cannot distinguish them from a
normal user watching a video.

The captured URLs can be passed to ffmpeg for direct download, avoiding
bot detection that yt-dlp triggers.
"""

from __future__ import annotations

import logging
import re
import time
from dataclasses import dataclass, field
from urllib.parse import parse_qs, urlencode, urlparse, urlunparse

from PySide6.QtCore import QObject, Signal
from PySide6.QtWebEngineCore import QWebEngineUrlRequestInterceptor

logger = logging.getLogger(__name__)

# Known audio-only itags (https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/youtube/_video.py)
_AUDIO_ITAGS = {
    139, 140, 141,       # m4a AAC
    171, 172,            # webm Vorbis
    249, 250, 251,       # webm Opus
    256, 258,            # m4a AAC HE
    325, 328,            # m4a AC-3 / E-AC-3
    338,                 # webm Opus (immersive)
}


@dataclass
class CapturedAudioStream:
    """A captured, pre-signed audio stream URL from googlevideo.com."""

    url: str                     # Full URL without range parameter
    video_id: str                # YouTube video ID
    itag: int = 0                # Stream format identifier
    mime_type: str = ""          # e.g. "audio/webm"
    expire_time: int = 0         # Unix timestamp from &expire= parameter
    captured_at: float = field(default_factory=time.time)

    @property
    def is_expired(self) -> bool:
        """Check if the URL has expired (with 60s safety margin)."""
        if self.expire_time == 0:
            return False
        return time.time() > self.expire_time - 60

    @property
    def seconds_until_expiry(self) -> float:
        """Seconds until expiry (negative if already expired)."""
        if self.expire_time == 0:
            return float("inf")
        return self.expire_time - 60 - time.time()


def _extract_video_id_from_url(url: str) -> str:
    """Extract YouTube video ID from a googlevideo.com URL.

    googlevideo.com URLs don't directly contain the YouTube video ID.
    We use the ``id`` parameter as a stable, unique stream identifier
    instead.  The actual YouTube video ID mapping is handled by the
    browser tab (which knows which page the user is watching).
    """
    params = parse_qs(urlparse(url).query)
    return params.get("id", [""])[0]


def _strip_range_params(url: str) -> str:
    """Remove byte-range parameters so ffmpeg downloads the full file.

    YouTube chunk requests include ``range``, ``rn`` (request number),
    and ``rbuf`` parameters that are only meaningful for MSE playback.
    """
    parsed = urlparse(url)
    params = parse_qs(parsed.query, keep_blank_values=True)
    for key in ("range", "rn", "rbuf"):
        params.pop(key, None)
    # Re-encode with doseq=True since parse_qs returns lists
    clean_query = urlencode(params, doseq=True)
    return urlunparse(parsed._replace(query=clean_query))


def _is_audio_request(url: str) -> bool:
    """Check if a googlevideo.com URL is for an audio stream."""
    params = parse_qs(urlparse(url).query)

    # Check mime parameter: mime=audio%2Fwebm or mime=audio%2Fmp4
    mime = params.get("mime", [""])[0]
    if mime.startswith("audio/"):
        return True

    # Fallback: check itag
    itag_str = params.get("itag", [""])[0]
    if itag_str.isdigit() and int(itag_str) in _AUDIO_ITAGS:
        return True

    return False


class MediaInterceptor(QWebEngineUrlRequestInterceptor):
    """Intercepts googlevideo.com media requests to capture audio URLs.

    Install on a QWebEngineProfile to passively capture audio stream
    URLs as the user browses YouTube.  The interceptor does NOT block
    or modify any requests — it only reads the URL.

    Signals:
        audio_captured(video_id, url): Emitted when a new audio stream
            URL is captured for a video.
    """

    # Signal must be on a QObject, not directly on the interceptor
    # (QWebEngineUrlRequestInterceptor IS a QObject in PySide6)
    audio_captured = Signal(str)  # clean_url

    def __init__(self, parent: QObject | None = None):
        super().__init__(parent)
        # Streams keyed by YouTube video ID (set externally by BrowserTab)
        self._streams: dict[str, CapturedAudioStream] = {}
        # The latest captured audio URL (before video_id mapping)
        self._latest_stream: CapturedAudioStream | None = None

    def interceptRequest(self, info):
        """Called for every HTTP request made by QWebEngine.

        IMPORTANT: This runs on Chromium's IO thread.  Must be fast
        and non-blocking — no file I/O, no heavy computation.
        """
        url = info.requestUrl()
        host = url.host()

        # Fast path: skip non-googlevideo requests
        if not host.endswith("googlevideo.com"):
            return

        url_str = url.toString()

        if not _is_audio_request(url_str):
            return

        # Strip range params to get a full-file download URL
        clean_url = _strip_range_params(url_str)

        # Extract metadata from URL params
        params = parse_qs(urlparse(url_str).query)
        stream_id = params.get("id", [""])[0]
        itag = int(params.get("itag", ["0"])[0] or 0)
        mime = params.get("mime", [""])[0]
        expire = int(params.get("expire", ["0"])[0] or 0)

        stream = CapturedAudioStream(
            url=clean_url,
            video_id=stream_id,  # googlevideo stream ID, not YT video ID
            itag=itag,
            mime_type=mime,
            expire_time=expire,
            captured_at=time.time(),
        )

        self._latest_stream = stream
        logger.debug(
            "Captured audio stream (itag=%d, mime=%s, expires in %.0fs)",
            itag, mime, stream.seconds_until_expiry,
        )
        self.audio_captured.emit(clean_url)

    def assign_video_id(self, video_id: str):
        """Associate the latest captured stream with a YouTube video ID.

        Called by BrowserTab when it knows which video is playing.
        """
        if self._latest_stream and video_id:
            self._streams[video_id] = self._latest_stream
            logger.debug(
                "Assigned stream to video %s (itag=%d)",
                video_id, self._latest_stream.itag,
            )

    def get_stream(self, video_id: str) -> CapturedAudioStream | None:
        """Get the captured audio stream for a video ID, if available."""
        stream = self._streams.get(video_id)
        if stream is None:
            return None
        if stream.is_expired:
            del self._streams[video_id]
            logger.debug("Expired stream for %s removed", video_id)
            return None
        return stream

    def get_all_streams(self) -> dict[str, CapturedAudioStream]:
        """Get all non-expired captured streams."""
        # Prune expired
        expired = [
            vid for vid, s in self._streams.items() if s.is_expired
        ]
        for vid in expired:
            del self._streams[vid]
        return dict(self._streams)

    def clear(self):
        """Clear all captured streams."""
        self._streams.clear()
        self._latest_stream = None
